-- Existing data retained. Backup first. Conflicts abort the whole transaction.
-- Generated by npm run sql:build. Supabase SQL Editor: run the WHOLE file.
BEGIN;
SET LOCAL lock_timeout='15s';
SET LOCAL statement_timeout='120s';
-- Supabase schema for AQUAGEO.KZ seminars platform
-- Run this file in Supabase SQL Editor after creating a project.

create extension if not exists pgcrypto;

-- Roles and block types
DO $$ BEGIN
  CREATE TYPE public.app_role AS ENUM ('admin', 'manager', 'student');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE public.content_block_type AS ENUM ('text', 'youtube', 'pdf', 'image');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;



-- Profiles are connected to auth.users. Students are created by public registration.
-- Managers are created by the create-manager Edge Function.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null unique,
  role public.app_role not null default 'student',
  organization text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  category text not null,
  date_text text not null,
  duration text not null,
  format text not null,
  location text not null,
  image_url text not null,
  short_description text not null,
  description text not null,
  outcomes text[] not null default '{}',
  lecturer_name text,
  lecturer_role text,
  lecturer_bio text,
  lecturer_photo text,
  certificate boolean not null default true,
  rating numeric(2,1) not null default 5.0,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.course_sections (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses(id) on delete cascade,
  title text not null,
  description text,
  position integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content_blocks (
  id uuid primary key default gen_random_uuid(),
  section_id uuid not null references public.course_sections(id) on delete cascade,
  type public.content_block_type not null,
  title text,
  content text,
  file_path text,
  position integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.enrollments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_id uuid not null references public.courses(id) on delete cascade,
  enrolled_at timestamptz not null default now(),
  completed_at timestamptz,
  certificate_requested_at timestamptz,
  unique(user_id, course_id)
);

create table if not exists public.section_progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  section_id uuid not null references public.course_sections(id) on delete cascade,
  is_completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, section_id)
);

create table if not exists public.certificate_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_id uuid not null references public.courses(id) on delete cascade,
  full_name text not null,
  course_title text not null,
  completed_at timestamptz not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_profiles_email on public.profiles(email);
create index if not exists idx_courses_slug on public.courses(slug);
create index if not exists idx_courses_created_by on public.courses(created_by);
create index if not exists idx_sections_course_position on public.course_sections(course_id, position);
create index if not exists idx_blocks_section_position on public.content_blocks(section_id, position);
create index if not exists idx_enrollments_user on public.enrollments(user_id);
create index if not exists idx_progress_user on public.section_progress(user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists courses_updated_at on public.courses;
create trigger courses_updated_at before update on public.courses
for each row execute function public.set_updated_at();

drop trigger if exists sections_updated_at on public.course_sections;
create trigger sections_updated_at before update on public.course_sections
for each row execute function public.set_updated_at();

drop trigger if exists blocks_updated_at on public.content_blocks;
create trigger blocks_updated_at before update on public.content_blocks
for each row execute function public.set_updated_at();

drop trigger if exists progress_updated_at on public.section_progress;
create trigger progress_updated_at before update on public.section_progress
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_role public.app_role := 'student';
  meta_full_name text;
begin
  if (new.raw_app_meta_data ->> 'role') in ('admin', 'manager', 'student') then
    profile_role := (new.raw_app_meta_data ->> 'role')::public.app_role;
  end if;

  meta_full_name := coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'fullName', split_part(new.email, '@', 1));

  insert into public.profiles (id, full_name, email, role)
  values (new.id, meta_full_name, lower(new.email), profile_role)
  on conflict (id) do update set
    email = excluded.email,
    full_name = coalesce(public.profiles.full_name, excluded.full_name),
    role = coalesce(public.profiles.role, excluded.role);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_auth_user();

create or replace function public.current_user_role()
returns public.app_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_email_taken(check_email text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles where email = lower(trim(check_email)));
$$;

create or replace function public.can_manage_course(check_course_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.courses c
    where c.id = check_course_id
      and (
        public.current_user_role() = 'admin'
        or (public.current_user_role() = 'manager' and c.created_by = auth.uid())
      )
  );
$$;

create or replace function public.is_enrolled(check_course_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.enrollments e
    where e.course_id = check_course_id and e.user_id = auth.uid()
  );
$$;

grant execute on function public.is_email_taken(text) to anon, authenticated;
grant execute on function public.current_user_role() to authenticated;
grant execute on function public.can_manage_course(uuid) to authenticated;
grant execute on function public.is_enrolled(uuid) to authenticated;

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.course_sections enable row level security;
alter table public.content_blocks enable row level security;
alter table public.enrollments enable row level security;
alter table public.section_progress enable row level security;
alter table public.certificate_requests enable row level security;

-- Basic table grants; RLS policies still restrict rows.
grant select on public.courses to anon, authenticated;
grant select on public.profiles to authenticated;
grant select, insert, update, delete on public.courses, public.course_sections, public.content_blocks, public.enrollments, public.section_progress, public.certificate_requests to authenticated;
revoke update on public.profiles from authenticated;
grant update (full_name, organization, phone) on public.profiles to authenticated;

-- Profiles
DROP POLICY IF EXISTS "profiles select own or admin" ON public.profiles;
CREATE POLICY "profiles select own or admin" ON public.profiles
FOR SELECT TO authenticated
USING (id = auth.uid() OR public.current_user_role() = 'admin');

DROP POLICY IF EXISTS "profiles update own editable fields" ON public.profiles;
CREATE POLICY "profiles update own editable fields" ON public.profiles
FOR UPDATE TO authenticated
USING (id = auth.uid())
WITH CHECK (id = auth.uid());

-- Courses: catalog is public, editing is role-based.
DROP POLICY IF EXISTS "courses public select" ON public.courses;
CREATE POLICY "courses public select" ON public.courses
FOR SELECT TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "courses insert managers" ON public.courses;
CREATE POLICY "courses insert managers" ON public.courses
FOR INSERT TO authenticated
WITH CHECK (created_by = auth.uid() AND public.current_user_role() IN ('admin', 'manager'));

DROP POLICY IF EXISTS "courses update managers" ON public.courses;
CREATE POLICY "courses update managers" ON public.courses
FOR UPDATE TO authenticated
USING (public.current_user_role() = 'admin' OR (public.current_user_role() = 'manager' AND created_by = auth.uid()))
WITH CHECK (public.current_user_role() = 'admin' OR (public.current_user_role() = 'manager' AND created_by = auth.uid()));

DROP POLICY IF EXISTS "courses delete managers" ON public.courses;
CREATE POLICY "courses delete managers" ON public.courses
FOR DELETE TO authenticated
USING (public.current_user_role() = 'admin' OR (public.current_user_role() = 'manager' AND created_by = auth.uid()));

-- Sections are visible only to enrolled students or course managers.
DROP POLICY IF EXISTS "sections select enrolled or manager" ON public.course_sections;
CREATE POLICY "sections select enrolled or manager" ON public.course_sections
FOR SELECT TO authenticated
USING (public.is_enrolled(course_id) OR public.can_manage_course(course_id));

DROP POLICY IF EXISTS "sections insert manager" ON public.course_sections;
CREATE POLICY "sections insert manager" ON public.course_sections
FOR INSERT TO authenticated
WITH CHECK (public.can_manage_course(course_id));

DROP POLICY IF EXISTS "sections update manager" ON public.course_sections;
CREATE POLICY "sections update manager" ON public.course_sections
FOR UPDATE TO authenticated
USING (public.can_manage_course(course_id))
WITH CHECK (public.can_manage_course(course_id));

DROP POLICY IF EXISTS "sections delete manager" ON public.course_sections;
CREATE POLICY "sections delete manager" ON public.course_sections
FOR DELETE TO authenticated
USING (public.can_manage_course(course_id));

-- Content blocks inherit permissions from their section/course.
DROP POLICY IF EXISTS "blocks select enrolled or manager" ON public.content_blocks;
CREATE POLICY "blocks select enrolled or manager" ON public.content_blocks
FOR SELECT TO authenticated
USING (exists (
  select 1 from public.course_sections s
  where s.id = section_id and (public.is_enrolled(s.course_id) or public.can_manage_course(s.course_id))
));

DROP POLICY IF EXISTS "blocks insert manager" ON public.content_blocks;
CREATE POLICY "blocks insert manager" ON public.content_blocks
FOR INSERT TO authenticated
WITH CHECK (exists (
  select 1 from public.course_sections s
  where s.id = section_id and public.can_manage_course(s.course_id)
));

DROP POLICY IF EXISTS "blocks update manager" ON public.content_blocks;
CREATE POLICY "blocks update manager" ON public.content_blocks
FOR UPDATE TO authenticated
USING (exists (
  select 1 from public.course_sections s
  where s.id = section_id and public.can_manage_course(s.course_id)
))
WITH CHECK (exists (
  select 1 from public.course_sections s
  where s.id = section_id and public.can_manage_course(s.course_id)
));

DROP POLICY IF EXISTS "blocks delete manager" ON public.content_blocks;
CREATE POLICY "blocks delete manager" ON public.content_blocks
FOR DELETE TO authenticated
USING (exists (
  select 1 from public.course_sections s
  where s.id = section_id and public.can_manage_course(s.course_id)
));

-- Enrollments
DROP POLICY IF EXISTS "enrollments select own or manager" ON public.enrollments;
CREATE POLICY "enrollments select own or manager" ON public.enrollments
FOR SELECT TO authenticated
USING (user_id = auth.uid() OR public.can_manage_course(course_id));

DROP POLICY IF EXISTS "enrollments insert own" ON public.enrollments;
CREATE POLICY "enrollments insert own" ON public.enrollments
FOR INSERT TO authenticated
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "enrollments update own" ON public.enrollments;
CREATE POLICY "enrollments update own" ON public.enrollments
FOR UPDATE TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- Section progress
DROP POLICY IF EXISTS "progress select own or manager" ON public.section_progress;
CREATE POLICY "progress select own or manager" ON public.section_progress
FOR SELECT TO authenticated
USING (user_id = auth.uid() OR exists (
  select 1 from public.course_sections s
  where s.id = section_id and public.can_manage_course(s.course_id)
));

DROP POLICY IF EXISTS "progress insert own enrolled" ON public.section_progress;
CREATE POLICY "progress insert own enrolled" ON public.section_progress
FOR INSERT TO authenticated
WITH CHECK (user_id = auth.uid() AND exists (
  select 1 from public.course_sections s
  where s.id = section_id and public.is_enrolled(s.course_id)
));

DROP POLICY IF EXISTS "progress update own enrolled" ON public.section_progress;
CREATE POLICY "progress update own enrolled" ON public.section_progress
FOR UPDATE TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- Certificate requests
DROP POLICY IF EXISTS "certificate select own or manager" ON public.certificate_requests;
CREATE POLICY "certificate select own or manager" ON public.certificate_requests
FOR SELECT TO authenticated
USING (user_id = auth.uid() OR public.can_manage_course(course_id));

DROP POLICY IF EXISTS "certificate insert own" ON public.certificate_requests;
CREATE POLICY "certificate insert own" ON public.certificate_requests
FOR INSERT TO authenticated
WITH CHECK (user_id = auth.uid());

-- Public bucket for course PDF files.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('course-files', 'course-files', true, 52428800, array['application/pdf','image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public = true, file_size_limit = 52428800, allowed_mime_types = array['application/pdf','image/jpeg','image/png','image/webp','image/gif'];

DROP POLICY IF EXISTS "course files public read" ON storage.objects;
CREATE POLICY "course files public read" ON storage.objects
FOR SELECT TO anon, authenticated
USING (bucket_id = 'course-files');

DROP POLICY IF EXISTS "course files manager insert" ON storage.objects;
CREATE POLICY "course files manager insert" ON storage.objects
FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'course-files' AND public.current_user_role() IN ('admin', 'manager'));

DROP POLICY IF EXISTS "course files manager update" ON storage.objects;
CREATE POLICY "course files manager update" ON storage.objects
FOR UPDATE TO authenticated
USING (bucket_id = 'course-files' AND public.current_user_role() IN ('admin', 'manager'))
WITH CHECK (bucket_id = 'course-files' AND public.current_user_role() IN ('admin', 'manager'));

DROP POLICY IF EXISTS "course files manager delete" ON storage.objects;
CREATE POLICY "course files manager delete" ON storage.objects
FOR DELETE TO authenticated
USING (bucket_id = 'course-files' AND public.current_user_role() IN ('admin', 'manager'));

-- Bootstrap first admin:
-- 1) Register normally on /signup.
-- 2) Run this query with your email:
-- update public.profiles set role = 'admin' where email = 'your-email@example.com';


-- Course testing module migration for existing AQUAGEO.KZ Supabase projects.
-- Run this file once in Supabase SQL Editor.

create table if not exists public.course_tests (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null unique references public.courses(id) on delete cascade,
  enabled boolean not null default true,
  passing_score integer not null default 70 check (passing_score in (60, 70, 80, 90, 100)),
  time_limit_minutes integer not null default 10 check (time_limit_minutes > 0),
  question_count integer not null default 0 check (question_count >= 0),
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.test_questions (
  id uuid primary key default gen_random_uuid(),
  test_id uuid not null references public.course_tests(id) on delete cascade,
  version integer not null check (version > 0),
  question_text text not null,
  position integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.test_options (
  id uuid primary key default gen_random_uuid(),
  question_id uuid not null references public.test_questions(id) on delete cascade,
  option_text text not null,
  position integer not null default 1,
  created_at timestamptz not null default now()
);

-- Correct answers are intentionally stored separately so students can never
-- download them together with normal test options.
create table if not exists public.test_question_answers (
  question_id uuid primary key references public.test_questions(id) on delete cascade,
  correct_option_id uuid not null references public.test_options(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.test_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_id uuid not null references public.courses(id) on delete cascade,
  test_id uuid not null references public.course_tests(id) on delete cascade,
  test_version integer not null,
  passing_score_snapshot integer not null,
  time_limit_minutes_snapshot integer not null,
  started_at timestamptz not null default now(),
  expires_at timestamptz not null,
  completed_at timestamptz,
  answers jsonb not null default '[]'::jsonb,
  correct_answers integer,
  total_questions integer,
  score integer,
  passed boolean,
  timed_out boolean not null default false,
  duration_seconds integer,
  created_at timestamptz not null default now()
);

create index if not exists idx_course_tests_course on public.course_tests(course_id);
create index if not exists idx_test_questions_version on public.test_questions(test_id, version, position);
create index if not exists idx_test_options_question on public.test_options(question_id, position);
create index if not exists idx_test_attempts_user_course on public.test_attempts(user_id, course_id, completed_at);
create index if not exists idx_test_attempts_test_version on public.test_attempts(test_id, test_version);

create or replace function public.set_course_test_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists course_tests_updated_at on public.course_tests;
create trigger course_tests_updated_at before update on public.course_tests
for each row execute function public.set_course_test_updated_at();

-- Returns true only when every course section has been acknowledged.
create or replace function public.course_content_completed(check_course_id uuid, check_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    count(s.id) > 0
    and count(s.id) = count(p.section_id) filter (where p.is_completed = true)
  from public.course_sections s
  left join public.section_progress p
    on p.section_id = s.id
   and p.user_id = check_user_id
  where s.course_id = check_course_id;
$$;

-- Students can read actual questions only while they have an active attempt.
-- Course owners/admins can always read the test for editing.
create or replace function public.can_view_test_version(check_test_id uuid, check_version integer)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.course_tests t
    where t.id = check_test_id
      and public.can_manage_course(t.course_id)
  ) or exists (
    select 1
    from public.test_attempts a
    where a.test_id = check_test_id
      and a.test_version = check_version
      and a.user_id = auth.uid()
      and a.completed_at is null
      and a.expires_at > now()
  );
$$;

-- Atomically saves a new version of a course test.
-- Old question versions are retained so historical attempts stay valid.
create or replace function public.save_course_test(
  check_course_id uuid,
  check_passing_score integer,
  check_time_limit_minutes integer,
  check_questions jsonb
)
returns table(test_id uuid, test_version integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_test_id uuid;
  target_version integer;
  question_item jsonb;
  option_item jsonb;
  question_pos bigint;
  option_pos bigint;
  question_id uuid;
  option_id uuid;
  correct_option_id uuid;
  correct_index integer;
  question_text_value text;
  option_text_value text;
  question_total integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  perform 1 from public.courses where id = check_course_id for update;
  if not public.can_manage_course(check_course_id) then
    raise exception 'You do not have permission to edit this course test';
  end if;

  if check_passing_score not in (60, 70, 80, 90, 100) then
    raise exception 'Passing score must be 60, 70, 80, 90 or 100';
  end if;

  if check_time_limit_minutes is null or check_time_limit_minutes <= 0 then
    raise exception 'Time limit must be greater than zero';
  end if;

  if check_questions is null or jsonb_typeof(check_questions) <> 'array' then
    raise exception 'Questions must be an array';
  end if;

  question_total := jsonb_array_length(check_questions);
  if question_total < 5 or question_total > 200 then
    raise exception 'A test must contain at least 5 questions';
  end if;

  insert into public.course_tests (
    course_id, enabled, passing_score, time_limit_minutes, question_count, version
  ) values (
    check_course_id, true, check_passing_score, check_time_limit_minutes, question_total, 1
  )
  on conflict (course_id) do update set
    enabled = true,
    passing_score = excluded.passing_score,
    time_limit_minutes = excluded.time_limit_minutes,
    question_count = excluded.question_count,
    version = public.course_tests.version + 1,
    updated_at = now()
  returning id, version into target_test_id, target_version;

  for question_item, question_pos in
    select value, ordinality
    from jsonb_array_elements(check_questions) with ordinality
  loop
    question_text_value := trim(coalesce(question_item->>'text', ''));
    if question_text_value = '' then
      raise exception 'Question % has no text', question_pos;
    end if;

    if coalesce(jsonb_typeof(question_item->'options'), '') <> 'array'
       or jsonb_array_length(question_item->'options') < 2
       or jsonb_array_length(question_item->'options') > 6 then
      raise exception 'Question % must contain from 2 to 6 answer options', question_pos;
    end if;

    correct_index := coalesce((question_item->>'correctOptionIndex')::integer, -1);
    if correct_index < 0 or correct_index >= jsonb_array_length(question_item->'options') then
      raise exception 'Question % has an invalid correct answer', question_pos;
    end if;

    insert into public.test_questions (test_id, version, question_text, position)
    values (target_test_id, target_version, question_text_value, question_pos)
    returning id into question_id;

    correct_option_id := null;
    for option_item, option_pos in
      select value, ordinality
      from jsonb_array_elements(question_item->'options') with ordinality
    loop
      option_text_value := trim(coalesce(option_item #>> '{}', ''));
      if option_text_value = '' then
        raise exception 'Question % contains an empty answer option', question_pos;
      end if;

      insert into public.test_options (question_id, option_text, position)
      values (question_id, option_text_value, option_pos)
      returning id into option_id;

      if option_pos - 1 = correct_index then
        correct_option_id := option_id;
      end if;
    end loop;

    if correct_option_id is null then
      raise exception 'Question % has no correct answer', question_pos;
    end if;

    insert into public.test_question_answers (question_id, correct_option_id)
    values (question_id, correct_option_id);
  end loop;

  return query select target_test_id, target_version;
end;
$$;

-- Creates a timed attempt only after the student has acknowledged all sections.
create or replace function public.start_course_test(check_course_id uuid)
returns table(
  attempt_id uuid,
  test_id uuid,
  test_version integer,
  started_at timestamptz,
  expires_at timestamptz,
  time_limit_minutes integer,
  passing_score integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_test public.course_tests%rowtype;
  new_attempt public.test_attempts%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not public.is_enrolled(check_course_id) then
    raise exception 'You must be enrolled in the course before taking the test';
  end if;

  if not public.course_content_completed(check_course_id, auth.uid()) then
    raise exception 'Complete all course sections before starting the test';
  end if;

  select * into target_test
  from public.course_tests
  where course_id = check_course_id and enabled = true;

  if target_test.id is null then
    raise exception 'The course test has not been configured yet';
  end if;

  if target_test.question_count < 5 then
    raise exception 'The course test is not ready';
  end if;

  insert into public.test_attempts (
    user_id, course_id, test_id, test_version,
    passing_score_snapshot, time_limit_minutes_snapshot,
    started_at, expires_at
  ) values (
    auth.uid(), check_course_id, target_test.id, target_test.version,
    target_test.passing_score, target_test.time_limit_minutes,
    clock_timestamp(), clock_timestamp() + make_interval(mins => target_test.time_limit_minutes)
  ) returning * into new_attempt;

  return query select
    new_attempt.id,
    new_attempt.test_id,
    new_attempt.test_version,
    new_attempt.started_at,
    new_attempt.expires_at,
    new_attempt.time_limit_minutes_snapshot,
    new_attempt.passing_score_snapshot;
end;
$$;

-- Scores an attempt entirely inside PostgreSQL. Correct answers are never sent to the browser.
create or replace function public.submit_course_test(check_attempt_id uuid, check_answers jsonb)
returns table(
  attempt_id uuid,
  score integer,
  correct_answers integer,
  total_questions integer,
  passed boolean,
  timed_out boolean,
  completed_at timestamptz,
  duration_seconds integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_attempt public.test_attempts%rowtype;
  answer_payload jsonb := coalesce(check_answers, '[]'::jsonb);
  total_value integer;
  correct_value integer;
  score_value integer;
  timed_out_value boolean;
  completed_value timestamptz := clock_timestamp();
  duration_value integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if jsonb_typeof(answer_payload) <> 'array' then
    raise exception 'Answers must be an array';
  end if;

  select * into target_attempt
  from public.test_attempts
  where id = check_attempt_id and user_id = auth.uid()
  for update;

  if target_attempt.id is null then
    raise exception 'Test attempt not found';
  end if;

  if target_attempt.completed_at is not null then
    raise exception 'This test attempt has already been submitted';
  end if;

  select count(*) into total_value
  from public.test_questions q
  where q.test_id = target_attempt.test_id
    and q.version = target_attempt.test_version;

  with submitted as (
    select distinct
      (item->>'question_id')::uuid as question_id,
      (item->>'option_id')::uuid as option_id
    from jsonb_array_elements(answer_payload) item
    where item ? 'question_id' and item ? 'option_id'
  )
  select count(*) into correct_value
  from submitted s
  join public.test_questions q
    on q.id = s.question_id
   and q.test_id = target_attempt.test_id
   and q.version = target_attempt.test_version
  join public.test_question_answers a
    on a.question_id = q.id
   and a.correct_option_id = s.option_id;

  if total_value <= 0 then
    score_value := 0;
  else
    score_value := round((correct_value * 100.0) / total_value)::integer;
  end if;

  timed_out_value := completed_value > target_attempt.expires_at;
  duration_value := greatest(0, round(extract(epoch from (completed_value - target_attempt.started_at)))::integer);

  update public.test_attempts set
    answers = answer_payload,
    correct_answers = correct_value,
    total_questions = total_value,
    score = score_value,
    passed = score_value >= target_attempt.passing_score_snapshot,
    timed_out = timed_out_value,
    completed_at = completed_value,
    duration_seconds = duration_value
  where id = target_attempt.id;

  return query select
    target_attempt.id,
    score_value,
    correct_value,
    total_value,
    score_value >= target_attempt.passing_score_snapshot,
    timed_out_value,
    completed_value,
    duration_value;
end;
$$;

alter table public.course_tests enable row level security;
alter table public.test_questions enable row level security;
alter table public.test_options enable row level security;
alter table public.test_question_answers enable row level security;
alter table public.test_attempts enable row level security;

grant select on public.course_tests, public.test_questions, public.test_options, public.test_question_answers, public.test_attempts to authenticated;
revoke insert, update, delete on public.course_tests, public.test_questions, public.test_options, public.test_question_answers, public.test_attempts from authenticated;

drop policy if exists "course tests select enrolled or manager" on public.course_tests;
create policy "course tests select enrolled or manager" on public.course_tests
for select to authenticated
using (public.is_enrolled(course_id) or public.can_manage_course(course_id));

drop policy if exists "test questions active attempt or manager" on public.test_questions;
create policy "test questions active attempt or manager" on public.test_questions
for select to authenticated
using (public.can_view_test_version(test_id, version));

drop policy if exists "test options active attempt or manager" on public.test_options;
create policy "test options active attempt or manager" on public.test_options
for select to authenticated
using (exists (
  select 1
  from public.test_questions q
  where q.id = question_id
    and public.can_view_test_version(q.test_id, q.version)
));

drop policy if exists "test answers manager only" on public.test_question_answers;
create policy "test answers manager only" on public.test_question_answers
for select to authenticated
using (exists (
  select 1
  from public.test_questions q
  join public.course_tests t on t.id = q.test_id
  where q.id = question_id
    and public.can_manage_course(t.course_id)
));

drop policy if exists "test attempts own or manager" on public.test_attempts;
create policy "test attempts own or manager" on public.test_attempts
for select to authenticated
using (user_id = auth.uid() or public.can_manage_course(course_id));

grant execute on function public.course_content_completed(uuid, uuid) to authenticated;
grant execute on function public.can_view_test_version(uuid, integer) to authenticated;
grant execute on function public.save_course_test(uuid, integer, integer, jsonb) to authenticated;
grant execute on function public.start_course_test(uuid) to authenticated;
grant execute on function public.submit_course_test(uuid, jsonb) to authenticated;


-- AQUAGEO.KZ security and concurrency hardening
-- Safe to run after the existing schema. Run once in Supabase SQL Editor.

-- Case-insensitive profile email uniqueness at the database layer.
create unique index if not exists profiles_email_lower_uidx
on public.profiles (lower(email));

-- Keep untrusted student-editable text bounded. NOT VALID preserves existing rows,
-- while PostgreSQL still enforces the checks for every new/updated row.
DO $$ BEGIN
  ALTER TABLE public.profiles ADD CONSTRAINT profiles_full_name_length_chk
    CHECK (char_length(btrim(full_name)) between 2 and 120) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.profiles ADD CONSTRAINT profiles_organization_length_chk
    CHECK (organization is null or char_length(organization) <= 200) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.profiles ADD CONSTRAINT profiles_phone_length_chk
    CHECK (phone is null or char_length(phone) <= 50) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.course_tests ADD CONSTRAINT course_tests_time_limit_cap_chk
    CHECK (time_limit_minutes between 1 and 480) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.course_tests ADD CONSTRAINT course_tests_question_count_cap_chk
    CHECK (question_count between 0 and 200) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.test_questions ADD CONSTRAINT test_questions_text_length_chk
    CHECK (char_length(btrim(question_text)) between 1 and 2000) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.test_options ADD CONSTRAINT test_options_text_length_chk
    CHECK (char_length(btrim(option_text)) between 1 and 1000) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Harden all existing SECURITY DEFINER helpers against search_path substitution,
-- and expose only the functions the authenticated client actually needs.
alter function public.handle_new_auth_user() set search_path = '';
alter function public.current_user_role() set search_path = '';
alter function public.is_email_taken(text) set search_path = '';
alter function public.can_manage_course(uuid) set search_path = '';
alter function public.is_enrolled(uuid) set search_path = '';
alter function public.can_view_test_version(uuid, integer) set search_path = '';
alter function public.save_course_test(uuid, integer, integer, jsonb) set search_path = '';
alter function public.set_updated_at() set search_path = '';
alter function public.set_course_test_updated_at() set search_path = '';

revoke execute on function public.handle_new_auth_user() from public, anon, authenticated;
revoke execute on function public.set_updated_at() from public, anon, authenticated;
revoke execute on function public.set_course_test_updated_at() from public, anon, authenticated;
revoke execute on function public.current_user_role() from public, anon;
revoke execute on function public.can_manage_course(uuid) from public, anon;
revoke execute on function public.is_enrolled(uuid) from public, anon;
revoke execute on function public.can_view_test_version(uuid, integer) from public, anon;
revoke execute on function public.save_course_test(uuid, integer, integer, jsonb) from public, anon;
grant execute on function public.current_user_role() to authenticated;
grant execute on function public.can_manage_course(uuid) to authenticated;
grant execute on function public.is_enrolled(uuid) to authenticated;
grant execute on function public.can_view_test_version(uuid, integer) to authenticated;
grant execute on function public.save_course_test(uuid, integer, integer, jsonb) to authenticated;

-- Do not expose account-existence checks to anonymous/authenticated clients.
revoke execute on function public.is_email_taken(text) from public, anon, authenticated;

-- Keep enrollment writes behind one atomic database function.
create or replace function public.enroll_in_course(check_course_id uuid)
returns public.enrollments
language plpgsql
security definer
set search_path = ''
as $$
declare
  target public.enrollments%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  perform 1 from public.courses c where c.id=check_course_id for share;
  if not exists (select 1 from public.courses c where c.id = check_course_id) then
    raise exception 'Course not found';
  end if;

  if exists(select 1 from public.courses c where c.id=check_course_id and c.archived_at is not null) then raise exception 'Course is archived'; end if;
  insert into public.enrollments (user_id, course_id)
  values (auth.uid(), check_course_id)
  on conflict (user_id, course_id) do nothing;

  select * into target
  from public.enrollments e
  where e.user_id = auth.uid() and e.course_id = check_course_id;

  return target;
end;
$$;

revoke execute on function public.enroll_in_course(uuid) from public, anon;
grant execute on function public.enroll_in_course(uuid) to authenticated;
revoke insert, update, delete on public.enrollments from authenticated;
grant select on public.enrollments to authenticated;

-- Section acknowledgements are also atomic and server-timestamped.
create or replace function public.mark_section_completed(check_section_id uuid)
returns public.section_progress
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_course_id uuid;
  target public.section_progress%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select s.course_id into target_course_id
  from public.course_sections s
  where s.id = check_section_id;

  if target_course_id is null then
    raise exception 'Course section not found';
  end if;
  perform 1 from public.courses where id = target_course_id for share;
  if not public.is_enrolled(target_course_id) then
    raise exception 'You must be enrolled in the course';
  end if;

  insert into public.section_progress (user_id, section_id, is_completed, completed_at)
  values (auth.uid(), check_section_id, true, clock_timestamp())
  on conflict (user_id, section_id) do update
    set is_completed = true,
        completed_at = coalesce(public.section_progress.completed_at, excluded.completed_at)
  returning * into target;

  if not exists(select 1 from public.course_tests where course_id=target_course_id and enabled)
    and public.course_content_completed(target_course_id,auth.uid()) then
    perform public.finalize_course_completion(target_course_id);
  end if;
  return target;
end;
$$;

revoke execute on function public.mark_section_completed(uuid) from public, anon;
grant execute on function public.mark_section_completed(uuid) to authenticated;
revoke insert, update, delete on public.section_progress from authenticated;
grant select on public.section_progress to authenticated;

-- A caller may check own completion; course managers may check their course.
create or replace function public.course_content_completed(check_course_id uuid, check_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when auth.uid() is null then false
    when check_user_id <> auth.uid() and not public.can_manage_course(check_course_id) then false
    else (
      select count(s.id) > 0
        and count(s.id) = count(p.section_id) filter (where p.is_completed = true)
      from public.course_sections s
      left join public.section_progress p
        on p.section_id = s.id
       and p.user_id = check_user_id
      where s.course_id = check_course_id
    )
  end;
$$;

revoke execute on function public.course_content_completed(uuid, uuid) from public, anon;
grant execute on function public.course_content_completed(uuid, uuid) to authenticated;

-- Marks a course complete only from trusted server-side facts (progress + a valid passed attempt).
create or replace function public.finalize_course_completion(check_course_id uuid)
returns public.enrollments
language plpgsql
security definer
set search_path = ''
as $$
declare
  completion_time timestamptz;
  target public.enrollments%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  perform 1 from public.courses where id=check_course_id for share;
  if not public.course_content_completed(check_course_id, auth.uid()) then
    raise exception 'Complete all course sections first';
  end if;

  select a.completed_at into completion_time
  from public.test_attempts a
  where a.user_id = auth.uid()
    and a.course_id = check_course_id
    and a.completed_at is not null
    and a.passed = true
    and a.timed_out = false
  order by a.score desc nulls last, a.completed_at desc
  limit 1;

  if not exists(select 1 from public.course_tests where course_id=check_course_id and enabled) then
    completion_time := clock_timestamp();
  end if;
  if completion_time is null then
    raise exception 'A passed non-expired test attempt is required';
  end if;

  update public.enrollments e
  set completed_at = coalesce(e.completed_at, completion_time)
  where e.user_id = auth.uid() and e.course_id = check_course_id
  returning * into target;

  if target.id is null then
    raise exception 'Enrollment not found';
  end if;

  return target;
end;
$$;

revoke execute on function public.finalize_course_completion(uuid) from public, anon;
grant execute on function public.finalize_course_completion(uuid) to authenticated;

-- Client-created certificate audit rows can contain forged payloads, so clients get read-only access.
revoke insert, update, delete on public.certificate_requests from authenticated;
grant select on public.certificate_requests to authenticated;

-- Clean up duplicate unfinished attempts left by older versions: keep the newest one.
with ranked_open_attempts as (
  select id,
         row_number() over (partition by user_id, course_id order by started_at desc, id desc) as rn
  from public.test_attempts
  where completed_at is null
)
update public.test_attempts a
set completed_at = clock_timestamp(),
    timed_out = true,
    passed = false,
    score = coalesce(a.score, 0),
    duration_seconds = greatest(0, round(extract(epoch from (clock_timestamp() - a.started_at)))::integer)
from ranked_open_attempts r
where a.id = r.id and r.rn > 1;

create unique index if not exists test_attempts_one_active_per_course_uidx
on public.test_attempts (user_id, course_id)
where completed_at is null;

-- One active test attempt per student/course. Simultaneous requests are serialized with an advisory lock.
create or replace function public.start_course_test(check_course_id uuid)
returns table(
  attempt_id uuid,
  test_id uuid,
  test_version integer,
  started_at timestamptz,
  expires_at timestamptz,
  time_limit_minutes integer,
  passing_score integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_test public.course_tests%rowtype;
  active_attempt public.test_attempts%rowtype;
  new_attempt public.test_attempts%rowtype;
  now_value timestamptz := clock_timestamp();
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  perform 1 from public.courses where id = check_course_id for share;
  perform pg_advisory_xact_lock(hashtext(auth.uid()::text), hashtext(check_course_id::text));
  now_value := clock_timestamp();

  if not public.is_enrolled(check_course_id) then
    raise exception 'You must be enrolled in the course before taking the test';
  end if;

  perform 1 from public.courses where id=check_course_id for share;
  if not public.course_content_completed(check_course_id, auth.uid()) then
    raise exception 'Complete all course sections before starting the test';
  end if;

  -- Close abandoned expired attempts so they cannot conflict with a new device/tab.
  update public.test_attempts a
  set completed_at = now_value,
      timed_out = true,
      passed = false,
      score = coalesce(a.score, 0),
      duration_seconds = greatest(0, round(extract(epoch from (now_value - a.started_at)))::integer)
  where a.user_id = auth.uid()
    and a.course_id = check_course_id
    and a.completed_at is null
    and a.expires_at <= now_value;

  select * into active_attempt
  from public.test_attempts a
  where a.user_id = auth.uid()
    and a.course_id = check_course_id
    and a.completed_at is null
    and a.expires_at > now_value
  order by a.started_at desc
  limit 1
  for update;

  if active_attempt.id is not null then
    return query select
      active_attempt.id,
      active_attempt.test_id,
      active_attempt.test_version,
      active_attempt.started_at,
      active_attempt.expires_at,
      active_attempt.time_limit_minutes_snapshot,
      active_attempt.passing_score_snapshot;
    return;
  end if;

  select * into target_test
  from public.course_tests t
  where t.course_id = check_course_id and t.enabled = true
  for share;

  if target_test.id is null then
    raise exception 'The course test has not been configured yet';
  end if;

  if target_test.question_count < 1 then
    raise exception 'The course test is not ready';
  end if;

  if (select count(*) from public.test_attempts quota where quota.user_id = auth.uid() and quota.course_id = check_course_id and quota.started_at > now_value - interval '24 hours') >= 10 then
    raise exception 'ATTEMPT_LIMIT';
  end if;

  insert into public.test_attempts (
    user_id, course_id, test_id, test_version,
    passing_score_snapshot, time_limit_minutes_snapshot,
    started_at, expires_at
  ) values (
    auth.uid(), check_course_id, target_test.id, target_test.version,
    target_test.passing_score, target_test.time_limit_minutes,
    now_value, now_value + make_interval(mins => target_test.time_limit_minutes)
  ) returning * into new_attempt;

  return query select
    new_attempt.id,
    new_attempt.test_id,
    new_attempt.test_version,
    new_attempt.started_at,
    new_attempt.expires_at,
    new_attempt.time_limit_minutes_snapshot,
    new_attempt.passing_score_snapshot;
end;
$$;

revoke execute on function public.start_course_test(uuid) from public, anon;
grant execute on function public.start_course_test(uuid) to authenticated;

-- Score a test fully in PostgreSQL. Exactly one valid option is accepted per answered question.
create or replace function public.submit_course_test(check_attempt_id uuid, check_answers jsonb)
returns table(
  attempt_id uuid,
  score integer,
  correct_answers integer,
  total_questions integer,
  passed boolean,
  timed_out boolean,
  completed_at timestamptz,
  duration_seconds integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_attempt public.test_attempts%rowtype;
  answer_payload jsonb := coalesce(check_answers, '[]'::jsonb);
  total_value integer;
  submitted_value integer;
  valid_value integer;
  correct_value integer;
  score_value integer;
  passed_value boolean;
  timed_out_value boolean;
  completed_value timestamptz;
  duration_value integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if jsonb_typeof(answer_payload) <> 'array' then
    raise exception 'Answers must be an array';
  end if;

  select * into target_attempt
  from public.test_attempts a
  where a.id = check_attempt_id and a.user_id = auth.uid()
  for update;

  if target_attempt.id is null then
    raise exception 'Test attempt not found';
  end if;

  completed_value := clock_timestamp();
  if target_attempt.completed_at is not null then
    raise exception 'This test attempt has already been submitted';
  end if;

  select count(*) into total_value
  from public.test_questions q
  where q.test_id = target_attempt.test_id
    and q.version = target_attempt.test_version;

  if jsonb_array_length(answer_payload) > total_value then
    raise exception 'Too many answers were submitted';
  end if;

  -- Duplicate answers to the same question are rejected instead of letting a caller submit every option.
  if exists (
    select 1
    from (
      select (item->>'question_id')::uuid as question_id, count(*) as cnt
      from jsonb_array_elements(answer_payload) item
      where item ? 'question_id' and item ? 'option_id'
      group by (item->>'question_id')::uuid
      having count(*) > 1
    ) duplicates
  ) then
    raise exception 'Only one answer per question is allowed';
  end if;

  with submitted as (
    select
      (item->>'question_id')::uuid as question_id,
      (item->>'option_id')::uuid as option_id
    from jsonb_array_elements(answer_payload) item
    where item ? 'question_id' and item ? 'option_id'
  ), valid as (
    select s.question_id, s.option_id
    from submitted s
    join public.test_questions q
      on q.id = s.question_id
     and q.test_id = target_attempt.test_id
     and q.version = target_attempt.test_version
    join public.test_options o
      on o.id = s.option_id
     and o.question_id = q.id
  )
  select (select count(*) from submitted), (select count(*) from valid)
  into submitted_value, valid_value;

  if submitted_value <> jsonb_array_length(answer_payload) or valid_value <> submitted_value then
    raise exception 'Submitted answers contain invalid question or option identifiers';
  end if;

  with submitted as (
    select
      (item->>'question_id')::uuid as question_id,
      (item->>'option_id')::uuid as option_id
    from jsonb_array_elements(answer_payload) item
  )
  select count(*) into correct_value
  from submitted s
  join public.test_questions q
    on q.id = s.question_id
   and q.test_id = target_attempt.test_id
   and q.version = target_attempt.test_version
  join public.test_question_answers a
    on a.question_id = q.id
   and a.correct_option_id = s.option_id;

  if total_value <= 0 then
    score_value := 0;
  else
    score_value := round((correct_value * 100.0) / total_value)::integer;
  end if;

  timed_out_value := completed_value >= target_attempt.expires_at;
  passed_value := (not timed_out_value) and score_value >= target_attempt.passing_score_snapshot;
  duration_value := greatest(0, round(extract(epoch from (completed_value - target_attempt.started_at)))::integer);

  update public.test_attempts a set
    answers = answer_payload,
    correct_answers = correct_value,
    total_questions = total_value,
    score = score_value,
    passed = passed_value,
    timed_out = timed_out_value,
    completed_at = completed_value,
    duration_seconds = duration_value
  where a.id = target_attempt.id;

  return query select
    target_attempt.id,
    score_value,
    correct_value,
    total_value,
    passed_value,
    timed_out_value,
    completed_value,
    duration_value;
end;
$$;

revoke execute on function public.submit_course_test(uuid, jsonb) from public, anon;
grant execute on function public.submit_course_test(uuid, jsonb) to authenticated;

-- Restrict course files to authenticated users who own the upload or can access the linked course.
create or replace function public.can_access_course_file(check_path text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.content_blocks b
    join public.course_sections s on s.id = b.section_id
    where b.file_path = check_path
      and (public.is_enrolled(s.course_id) or public.can_manage_course(s.course_id))
  );
$$;

create or replace function public.can_manage_course_file(check_path text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.content_blocks b
    join public.course_sections s on s.id = b.section_id
    where b.file_path = check_path
      and public.can_manage_course(s.course_id)
  );
$$;

revoke execute on function public.can_access_course_file(text) from public, anon;
revoke execute on function public.can_manage_course_file(text) from public, anon;
grant execute on function public.can_access_course_file(text) to authenticated;
grant execute on function public.can_manage_course_file(text) to authenticated;

update storage.buckets
set public = false,
    file_size_limit = 26214400,
    allowed_mime_types = array['application/pdf','image/jpeg','image/png','image/webp','image/gif']
where id = 'course-files';

DROP POLICY IF EXISTS "course files public read" ON storage.objects;
DROP POLICY IF EXISTS "course files authenticated read" ON storage.objects;
CREATE POLICY "course files authenticated read" ON storage.objects
FOR SELECT TO authenticated
USING (
  bucket_id = 'course-files'
  and (
    owner_id = auth.uid()::text
    or public.can_access_course_file(name)
  )
);

DROP POLICY IF EXISTS "course files manager insert" ON storage.objects;
CREATE POLICY "course files manager insert" ON storage.objects
FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'course-files'
  and public.current_user_role() in ('admin', 'manager')
  and owner_id = auth.uid()::text
);

DROP POLICY IF EXISTS "course files manager update" ON storage.objects;
CREATE POLICY "course files manager update" ON storage.objects
FOR UPDATE TO authenticated
USING (
  bucket_id = 'course-files'
  and public.current_user_role() in ('admin', 'manager')
  and (owner_id = auth.uid()::text or public.can_manage_course_file(name))
)
WITH CHECK (
  bucket_id = 'course-files'
  and public.current_user_role() in ('admin', 'manager')
);

DROP POLICY IF EXISTS "course files manager delete" ON storage.objects;
CREATE POLICY "course files manager delete" ON storage.objects
FOR DELETE TO authenticated
USING (
  bucket_id = 'course-files'
  and public.current_user_role() in ('admin', 'manager')
  and (owner_id = auth.uid()::text or public.can_manage_course_file(name))
);
-- Course editing is one transaction: course + sections + blocks + test.
-- expected_updated_at provides optimistic concurrency protection against stale editor tabs/devices.
create or replace function public.save_course_with_content(
  check_course_id uuid,
  check_expected_updated_at timestamptz,
  check_payload jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  course_id_value uuid := check_course_id;
  owner_id_value uuid;
  old_updated_at timestamptz;
  payload_slug text;
  payload_title text;
  section_item jsonb;
  block_item jsonb;
  test_item jsonb;
  section_pos bigint;
  block_pos bigint;
  section_id_value uuid;
  block_id_value uuid;
  section_ids uuid[] := array[]::uuid[];
  block_ids uuid[];
  block_type_value public.content_block_type;
  file_path_value text;
  content_value text;
  has_test boolean;
  hours_value integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if coalesce(public.current_user_role()::text, '') not in ('admin', 'manager') then
    raise exception 'Only admin or manager can edit courses';
  end if;

  if check_payload is null or jsonb_typeof(check_payload) <> 'object' then
    raise exception 'Course payload must be an object';
  end if;
  if pg_column_size(check_payload) > 2097152 then
    raise exception 'Course payload is too large';
  end if;

  payload_title := btrim(coalesce(check_payload->>'title', ''));
  payload_slug := btrim(lower(coalesce(check_payload->>'slug', '')));
  if char_length(payload_title) < 1 or char_length(payload_title) > 300 then
    raise exception 'Course title must contain 1-300 characters';
  end if;
  if char_length(payload_slug) < 1 or char_length(payload_slug) > 160 or payload_slug !~ '^[a-z0-9а-яё-]+$' then
    raise exception 'Course slug is invalid';
  end if;
  if jsonb_typeof(coalesce(check_payload->'sections', '[]'::jsonb)) <> 'array' then
    raise exception 'Course sections must be an array';
  end if;
  if jsonb_array_length(coalesce(check_payload->'sections', '[]'::jsonb)) > 100 then
    raise exception 'A course cannot contain more than 100 sections';
  end if;

  test_item := check_payload->'test';
  if test_item is not null and jsonb_typeof(test_item) not in ('object','null') then raise exception 'Invalid test settings'; end if;
  has_test := coalesce(jsonb_typeof(test_item)='object' and coalesce((test_item->>'enabled')::boolean,true),false);
  hours_value := nullif(check_payload->>'academicHours','')::integer;
  if hours_value is not null and hours_value not between 1 and 10000 then raise exception 'Invalid academic hours'; end if;

  if course_id_value is null then
    insert into public.courses (
      slug, title, category, date_text, duration, format, location,
      image_url, short_description, description, outcomes,
      lecturer_name, lecturer_role, lecturer_bio, lecturer_photo,
      certificate, academic_hours, rating, created_by
    ) values (
      payload_slug,
      payload_title,
      left(btrim(coalesce(check_payload->>'category', '')), 160),
      left(btrim(coalesce(check_payload->>'date', '')), 160),
      left(btrim(coalesce(check_payload->>'duration', '')), 100),
      left(btrim(coalesce(check_payload->>'format', '')), 100),
      left(btrim(coalesce(check_payload->>'location', '')), 240),
      left(btrim(coalesce(check_payload->>'image', '')), 2000),
      left(btrim(coalesce(check_payload->>'shortDescription', '')), 1000),
      left(btrim(coalesce(check_payload->>'description', '')), 20000),
      coalesce(array(select jsonb_array_elements_text(coalesce(check_payload->'outcomes', '[]'::jsonb))), '{}'::text[]),
      left(btrim(coalesce(check_payload#>>'{lecturer,name}', '')), 200),
      left(btrim(coalesce(check_payload#>>'{lecturer,role}', '')), 200),
      left(btrim(coalesce(check_payload#>>'{lecturer,bio}', '')), 5000),
      left(btrim(coalesce(check_payload#>>'{lecturer,photo}', '')), 2000),
      has_test,
      hours_value,
      greatest(0, least(5, coalesce((check_payload->>'rating')::numeric, 5))),
      auth.uid()
    )
    returning id into course_id_value;
  else
    select c.created_by, c.updated_at
      into owner_id_value, old_updated_at
    from public.courses c
    where c.id = course_id_value
    for update;

    if owner_id_value is null then
      raise exception 'Course not found';
    end if;
    if not public.can_manage_course(course_id_value) then
      raise exception 'You do not have permission to edit this course';
    end if;
    if check_expected_updated_at is null or old_updated_at <> check_expected_updated_at then
      raise exception 'COURSE_EDIT_CONFLICT';
    end if;

    update public.courses c set
      slug = payload_slug,
      title = payload_title,
      category = left(btrim(coalesce(check_payload->>'category', '')), 160),
      date_text = left(btrim(coalesce(check_payload->>'date', '')), 160),
      duration = left(btrim(coalesce(check_payload->>'duration', '')), 100),
      format = left(btrim(coalesce(check_payload->>'format', '')), 100),
      location = left(btrim(coalesce(check_payload->>'location', '')), 240),
      image_url = left(btrim(coalesce(check_payload->>'image', '')), 2000),
      short_description = left(btrim(coalesce(check_payload->>'shortDescription', '')), 1000),
      description = left(btrim(coalesce(check_payload->>'description', '')), 20000),
      outcomes = coalesce(array(select jsonb_array_elements_text(coalesce(check_payload->'outcomes', '[]'::jsonb))), '{}'::text[]),
      lecturer_name = left(btrim(coalesce(check_payload#>>'{lecturer,name}', '')), 200),
      lecturer_role = left(btrim(coalesce(check_payload#>>'{lecturer,role}', '')), 200),
      lecturer_bio = left(btrim(coalesce(check_payload#>>'{lecturer,bio}', '')), 5000),
      lecturer_photo = left(btrim(coalesce(check_payload#>>'{lecturer,photo}', '')), 2000),
      certificate = has_test,
      academic_hours = hours_value,
      rating = greatest(0, least(5, coalesce((check_payload->>'rating')::numeric, 5)))
    where c.id = course_id_value;
  end if;

  for section_item, section_pos in
    select value, ordinality
    from jsonb_array_elements(coalesce(check_payload->'sections', '[]'::jsonb)) with ordinality
  loop
    if nullif(section_item->>'id', '') is not null then
      section_id_value := (section_item->>'id')::uuid;
      if section_id_value = any(section_ids) then raise exception 'Duplicate section'; end if;
      if not exists (
        select 1 from public.course_sections s
        where s.id = section_id_value and s.course_id = course_id_value
      ) then
        raise exception 'A section does not belong to this course';
      end if;
      update public.course_sections s set
        title = left(btrim(coalesce(section_item->>'title', '')), 300),
        description = left(btrim(coalesce(section_item->>'description', '')), 10000),
        position = section_pos
      where s.id = section_id_value;
    else
      insert into public.course_sections (course_id, title, description, position)
      values (
        course_id_value,
        left(btrim(coalesce(section_item->>'title', '')), 300),
        left(btrim(coalesce(section_item->>'description', '')), 10000),
        section_pos
      ) returning id into section_id_value;
    end if;

    if btrim(coalesce(section_item->>'title', '')) = '' then
      raise exception 'Section title cannot be empty';
    end if;

    section_ids := array_append(section_ids, section_id_value);
    block_ids := array[]::uuid[];

    if jsonb_typeof(coalesce(section_item->'blocks', '[]'::jsonb)) <> 'array' then
      raise exception 'Section blocks must be an array';
    end if;
    if jsonb_array_length(coalesce(section_item->'blocks', '[]'::jsonb)) > 200 then
      raise exception 'A section cannot contain more than 200 blocks';
    end if;

    for block_item, block_pos in
      select value, ordinality
      from jsonb_array_elements(coalesce(section_item->'blocks', '[]'::jsonb)) with ordinality
    loop
      block_type_value := (block_item->>'type')::public.content_block_type;
      file_path_value := nullif(btrim(coalesce(block_item->>'filePath', '')), '');
      content_value := left(coalesce(block_item->>'content', ''), 100000);

      if file_path_value is not null then
        if char_length(file_path_value) > 500 or file_path_value like '%..%' or left(file_path_value, 1) = '/' then
          raise exception 'Invalid course file path';
        end if;
        if not exists (
          select 1
          from storage.objects o
          where o.bucket_id = 'course-files'
            and o.name = file_path_value
            and (
              (o.owner_id = auth.uid()::text or split_part(o.name, '/', 1) = auth.uid()::text)
              or public.current_user_role() = 'admin'
              or exists (
                select 1
                from public.content_blocks old_b
                join public.course_sections old_s on old_s.id = old_b.section_id
                where old_b.file_path = file_path_value
                  and old_s.course_id = course_id_value
              )
            )
        ) then
          raise exception 'Course file is missing or is not owned by this editor';
        end if;
      end if;

      if block_type_value in ('pdf','image','youtube') and file_path_value is null and content_value<>'' and content_value !~ '^https?://' then raise exception 'Material URL must use HTTPS or HTTP'; end if;

      -- Signed/private Storage URLs are bearer credentials. Never persist them in content.
      if file_path_value is not null and block_type_value in ('pdf', 'image') then
        content_value := '';
      end if;

      if nullif(block_item->>'id', '') is not null then
        block_id_value := (block_item->>'id')::uuid;
        if block_id_value = any(block_ids) then raise exception 'Duplicate block'; end if;
        if not exists (
          select 1 from public.content_blocks b
          where b.id = block_id_value and b.section_id = section_id_value
        ) then
          raise exception 'A content block does not belong to this section';
        end if;
        update public.content_blocks b set
          type = block_type_value,
          title = left(btrim(coalesce(block_item->>'title', '')), 500),
          content = content_value,
          file_path = file_path_value,
          position = block_pos
        where b.id = block_id_value;
      else
        insert into public.content_blocks (section_id, type, title, content, file_path, position)
        values (
          section_id_value,
          block_type_value,
          left(btrim(coalesce(block_item->>'title', '')), 500),
          content_value,
          file_path_value,
          block_pos
        ) returning id into block_id_value;
      end if;

      block_ids := array_append(block_ids, block_id_value);
    end loop;

    delete from public.content_blocks b
    where b.section_id = section_id_value
      and not (b.id = any(block_ids));
  end loop;

  if exists (select 1 from public.course_sections s join public.section_progress p on p.section_id=s.id where s.course_id=course_id_value and not (s.id=any(section_ids))) then
    raise exception 'SECTION_HAS_PROGRESS';
  end if;

  delete from public.course_sections s
  where s.course_id = course_id_value
    and not (s.id = any(section_ids));

  test_item := check_payload->'test';
  if has_test then
    perform 1
    from public.save_course_test(
      course_id_value,
      coalesce((test_item->>'passingScore')::integer, 70),
      coalesce((test_item->>'timeLimitMinutes')::integer, 10),
      coalesce(test_item->'questions', '[]'::jsonb)
    );
  else
    update public.course_tests set enabled=false where course_id=course_id_value;
    update public.enrollments e set completed_at=coalesce(e.completed_at,clock_timestamp())
    where e.course_id=course_id_value and public.course_content_completed(course_id_value,e.user_id);
  end if;

  return course_id_value;
end;
$$;

revoke execute on function public.save_course_with_content(uuid, timestamptz, jsonb) from public, anon;
grant execute on function public.save_course_with_content(uuid, timestamptz, jsonb) to authenticated;

-- Force course mutations through the transactional RPC above.
revoke insert, update, delete on public.courses from authenticated;
revoke insert, update, delete on public.course_sections from authenticated;
revoke insert, update, delete on public.content_blocks from authenticated;
grant select on public.courses, public.course_sections, public.content_blocks to authenticated;

-- Remove stale public/signed bearer URLs from private file blocks.
update public.content_blocks
set content = ''
where file_path is not null and type in ('pdf', 'image');

-- Refresh Supabase/PostgREST RPC metadata after creating or replacing functions.
notify pgrst, 'reload schema';

-- Release 2: authoritative certificates, restricted writes, history and API metadata.
create table if not exists public.app_settings (
 id boolean primary key default true check(id),
 issuer_name text not null default 'AQUAGEO.KZ' check(length(issuer_name) between 1 and 160)
);
insert into public.app_settings(id) values(true) on conflict do nothing;
alter table public.app_settings enable row level security;
revoke all on public.app_settings from public, anon, authenticated;

create table if not exists public.certificates (
 id uuid primary key default gen_random_uuid(),
 certificate_number text not null unique default ('AQ-' || upper(replace(gen_random_uuid()::text,'-',''))),
 user_id uuid not null references public.profiles(id) on delete restrict,
 course_id uuid not null references public.courses(id) on delete restrict,
 full_name_snapshot text not null,
 course_title_snapshot text not null,
 score_snapshot integer check(score_snapshot between 0 and 100),
 issuer_snapshot text not null,
 issued_at timestamptz not null default clock_timestamp(),
 created_at timestamptz not null default clock_timestamp(),
 status text not null default 'active' check(status in ('active','revoked')),
 template_version integer not null default 2,
 unique(user_id,course_id),
 check(certificate_number ~ '^[A-Za-z0-9_-]{8,128}$')
);
create table if not exists public.certificate_pdfs (
 certificate_number text primary key references public.certificates(certificate_number) on delete restrict,
 pdf_base64 text not null check(length(pdf_base64) <= 4000000),
 sha256 text not null check(sha256 ~ '^[a-f0-9]{64}$'),
 verification_url text not null,
 created_at timestamptz not null default clock_timestamp()
);
-- Old records are preserved byte-for-byte as private JSON; only whitelisted fields are served.
create table if not exists public.legacy_certificates (
 certificate_number text primary key,
 record jsonb not null,
 imported_at timestamptz not null default clock_timestamp()
);
create table if not exists public.audit_log (
 id bigint generated always as identity primary key,
 actor_id uuid,
 action text not null,
 entity_table text not null,
 entity_id text not null,
 created_at timestamptz not null default clock_timestamp()
);
create index if not exists audit_log_created_idx on public.audit_log(created_at desc);
create table if not exists public.course_revisions (
 course_id uuid not null references public.courses(id) on delete restrict,
 revision bigint not null,
 snapshot jsonb not null,
 actor_id uuid,
 created_at timestamptz not null default clock_timestamp(),
 primary key(course_id,revision)
);
alter table public.courses add column if not exists revision bigint not null default 1;
alter table public.courses add column if not exists archived_at timestamptz;

alter table public.certificates enable row level security;
alter table public.certificate_pdfs enable row level security;
alter table public.legacy_certificates enable row level security;
alter table public.audit_log enable row level security;
alter table public.course_revisions enable row level security;
revoke all on public.certificates,public.certificate_pdfs,public.legacy_certificates,public.audit_log,public.course_revisions from public,anon,authenticated;
grant select on public.certificates,public.audit_log,public.course_revisions to authenticated;
grant all on public.certificates,public.certificate_pdfs,public.legacy_certificates,public.audit_log,public.course_revisions,public.app_settings to service_role;
grant usage on sequence public.audit_log_id_seq to service_role;
drop policy if exists certificates_owner on public.certificates;
create policy certificates_owner on public.certificates for select to authenticated using(user_id=auth.uid() or public.can_manage_course(course_id));
drop policy if exists audit_admin on public.audit_log;
create policy audit_admin on public.audit_log for select to authenticated using(public.current_user_role()='admin');
drop policy if exists revisions_manager on public.course_revisions;
create policy revisions_manager on public.course_revisions for select to authenticated using(public.can_manage_course(course_id));

create or replace function public.protect_certificate_snapshot() returns trigger
language plpgsql set search_path='' as $$
begin
 if (to_jsonb(new)-'status') is distinct from (to_jsonb(old)-'status') then
  raise exception 'Certificate snapshot is immutable';
 end if;
 return new;
end $$;
drop trigger if exists certificates_immutable on public.certificates;
create trigger certificates_immutable before update on public.certificates for each row execute function public.protect_certificate_snapshot();

create or replace function public.issue_certificate(check_course_id uuid)
returns public.certificates language plpgsql security definer set search_path='' as $$
declare target public.certificates%rowtype; c public.courses%rowtype; p public.profiles%rowtype; a public.test_attempts%rowtype;
begin
 if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
 select * into c from public.courses where id=check_course_id for share;
 if c.id is null then raise exception 'Course not found'; end if;
 perform pg_advisory_xact_lock(hashtext(auth.uid()::text),hashtext(check_course_id::text));
 select * into target from public.certificates where user_id=auth.uid() and course_id=check_course_id;
 if target.id is not null then return target; end if;
 if not c.certificate or not exists(select 1 from public.course_tests where course_id=check_course_id and enabled) then raise exception 'CERTIFICATE_DISABLED'; end if;
 if not public.is_enrolled(check_course_id) or not public.course_content_completed(check_course_id,auth.uid()) then
  raise exception 'Complete all course sections first';
 end if;
 select * into a from public.test_attempts where user_id=auth.uid() and course_id=check_course_id
  and passed=true and timed_out=false and completed_at is not null
  order by score desc,completed_at desc limit 1;
 if a.id is null then raise exception 'A passed non-expired test attempt is required'; end if;
 select * into p from public.profiles where id=auth.uid() for share;
 insert into public.certificates(user_id,course_id,full_name_snapshot,course_title_snapshot,score_snapshot,issuer_snapshot,academic_hours_snapshot,city_snapshot,template_version)
 values(auth.uid(),check_course_id,p.full_name,c.title,a.score,(select issuer_name from public.app_settings where id),c.academic_hours,'Астана',3)
 on conflict(user_id,course_id) do nothing returning * into target;
 if target.id is null then select * into target from public.certificates where user_id=auth.uid() and course_id=check_course_id; end if;
 update public.enrollments set completed_at=coalesce(completed_at,a.completed_at),certificate_requested_at=coalesce(certificate_requested_at,target.issued_at)
 where user_id=auth.uid() and course_id=check_course_id;
 return target;
end $$;
revoke all on function public.issue_certificate(uuid) from public,anon;
grant execute on function public.issue_certificate(uuid) to authenticated;

create or replace function public.audit_entity() returns trigger
language plpgsql security definer set search_path='' as $$
declare item jsonb := case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end;
begin
 insert into public.audit_log(actor_id,action,entity_table,entity_id)
 values(auth.uid(),lower(tg_op),tg_table_name,coalesce(item->>'id',item->>'certificate_number'));
 return case when tg_op='DELETE' then old else new end;
end $$;
drop trigger if exists certificates_audit on public.certificates;
create trigger certificates_audit after insert or update on public.certificates for each row execute function public.audit_entity();
drop trigger if exists courses_audit on public.courses;
create trigger courses_audit after insert or update or delete on public.courses for each row execute function public.audit_entity();
drop trigger if exists tests_audit on public.course_tests;
create trigger tests_audit after insert or update on public.course_tests for each row execute function public.audit_entity();
drop trigger if exists profiles_audit on public.profiles;
create trigger profiles_audit after update of role on public.profiles for each row execute function public.audit_entity();

create or replace function public.snapshot_course_revision() returns trigger
language plpgsql security definer set search_path='' as $$
begin
 insert into public.course_revisions(course_id,revision,actor_id,snapshot)
 values(old.id,old.revision,auth.uid(),jsonb_build_object('course',to_jsonb(old),
 'sections',(select coalesce(jsonb_agg(to_jsonb(s) || jsonb_build_object('blocks',
 (select coalesce(jsonb_agg(b),'[]') from public.content_blocks b where b.section_id=s.id))), '[]')
 from public.course_sections s where s.course_id=old.id))) on conflict do nothing;
 new.revision := old.revision+1;
 new.updated_at := clock_timestamp();
 return new;
end $$;
drop trigger if exists courses_revision on public.courses;
create trigger courses_revision before update on public.courses for each row execute function public.snapshot_course_revision();

create or replace function public.archive_course(check_course_id uuid,check_expected_updated_at timestamptz)
returns void language plpgsql security definer set search_path='' as $$
declare c public.courses%rowtype;
begin
 if auth.uid() is null or not public.can_manage_course(check_course_id) then raise exception 'Forbidden' using errcode='42501'; end if;
 select * into c from public.courses where id=check_course_id for update;
 if check_expected_updated_at is null or c.updated_at<>check_expected_updated_at then raise exception 'COURSE_EDIT_CONFLICT'; end if;
 update public.courses set archived_at=clock_timestamp() where id=c.id;
end $$;
revoke all on function public.archive_course(uuid,timestamptz) from public,anon;
grant execute on function public.archive_course(uuid,timestamptz) to authenticated;
-- Direct test edits bypass the editor's optimistic concurrency token: disable them.
revoke all on function public.save_course_test(uuid,integer,integer,jsonb) from public,anon,authenticated;

-- Rebuild policies on application-owned tables, so unknown old permissive policies cannot survive.
-- Canonical read policies remain; every mutation except profile fields uses RPC.
do $$ declare r record; begin
 for r in select schemaname,tablename,policyname from pg_policies where schemaname='public'
 and tablename in ('profiles','courses','course_sections','content_blocks','enrollments','section_progress','certificate_requests','course_tests','test_questions','test_options','test_question_answers','test_attempts')
 loop execute format('drop policy %I on %I.%I',r.policyname,r.schemaname,r.tablename); end loop;
end $$;
create policy profile_read on public.profiles for select to authenticated using(id=auth.uid() or public.current_user_role()='admin');
create policy profile_edit on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy course_read on public.courses for select to anon,authenticated using(true);
create policy section_read on public.course_sections for select to authenticated using(public.is_enrolled(course_id) or public.can_manage_course(course_id));
create policy block_read on public.content_blocks for select to authenticated using(exists(select 1 from public.course_sections s where s.id=section_id and (public.is_enrolled(s.course_id) or public.can_manage_course(s.course_id))));
create policy enrollment_read on public.enrollments for select to authenticated using(user_id=auth.uid() or public.can_manage_course(course_id));
create policy progress_read on public.section_progress for select to authenticated using(user_id=auth.uid() or exists(select 1 from public.course_sections s where s.id=section_id and public.can_manage_course(s.course_id)));
create policy request_read on public.certificate_requests for select to authenticated using(user_id=auth.uid() or public.can_manage_course(course_id));
create policy test_read on public.course_tests for select to authenticated using(public.is_enrolled(course_id) or public.can_manage_course(course_id));
create policy question_read on public.test_questions for select to authenticated using(public.can_view_test_version(test_id,version));
create policy option_read on public.test_options for select to authenticated using(exists(select 1 from public.test_questions q where q.id=question_id and public.can_view_test_version(q.test_id,q.version)));
create policy answer_read on public.test_question_answers for select to authenticated using(exists(select 1 from public.test_questions q join public.course_tests t on t.id=q.test_id where q.id=question_id and public.can_manage_course(t.course_id)));
create policy attempt_read on public.test_attempts for select to authenticated using(user_id=auth.uid() or public.can_manage_course(course_id));
-- Remove table and old column-level grants, including Supabase default grants.
do $$ declare r record; begin
 for r in select table_name,column_name from information_schema.columns where table_schema='public'
 and table_name in ('profiles','courses','course_sections','content_blocks','enrollments','section_progress','certificate_requests','course_tests','test_questions','test_options','test_question_answers','test_attempts') loop
 execute format('revoke insert(%I),update(%I),references(%I) on public.%I from public,anon,authenticated',r.column_name,r.column_name,r.column_name,r.table_name);
 end loop;
end $$;
revoke all on public.profiles,public.courses,public.course_sections,public.content_blocks,public.enrollments,public.section_progress,public.certificate_requests,public.course_tests,public.test_questions,public.test_options,public.test_question_answers,public.test_attempts from public,anon,authenticated;
grant select on public.courses to anon;
grant select on public.profiles,public.courses,public.course_sections,public.content_blocks,public.enrollments,public.section_progress,public.certificate_requests,public.course_tests,public.test_questions,public.test_options,public.test_question_answers,public.test_attempts to authenticated;
grant update(full_name,organization,phone) on public.profiles to authenticated;
-- Files are uploaded by Express after signature inspection. Direct Storage uploads are denied.
drop policy if exists "course files manager insert" on storage.objects;
drop policy if exists "course files manager update" on storage.objects;
drop policy if exists "course files manager delete" on storage.objects;
drop policy if exists "course files authenticated read" on storage.objects;
create policy "course files authenticated read" on storage.objects for select to authenticated
 using(bucket_id='course-files' and (public.can_access_course_file(name) or
 (coalesce(public.current_user_role()::text,'') in ('admin','manager') and (owner_id=auth.uid()::text or split_part(name,'/',1)=auth.uid()::text))));
-- Restrictive policies also stop unknown old policies from reopening this bucket.
drop policy if exists course_files_write_fence on storage.objects;
create policy course_files_write_fence on storage.objects as restrictive for all to anon,authenticated
 using(bucket_id<>'course-files' or (auth.uid() is not null and (public.can_access_course_file(name) or
 (coalesce(public.current_user_role()::text,'') in ('admin','manager') and (owner_id=auth.uid()::text or split_part(name,'/',1)=auth.uid()::text)))))
 with check(bucket_id<>'course-files');
-- DELETE needs its own restrictive fence (ALL USING above allows reads).
drop policy if exists course_files_delete_fence on storage.objects;
create policy course_files_delete_fence on storage.objects as restrictive for delete to anon,authenticated using(bucket_id<>'course-files');

-- Referential checks preserve existing data, while enforcing all new writes immediately.
create unique index if not exists test_options_question_id_id_uidx on public.test_options(question_id,id);
do $$ begin
 alter table public.test_question_answers add constraint correct_option_belongs_to_question
 foreign key(question_id,correct_option_id) references public.test_options(question_id,id) not valid;
exception when duplicate_object then null; end $$;
create unique index if not exists course_tests_course_id_id_uidx on public.course_tests(course_id,id);
do $$ begin
 alter table public.test_attempts add constraint attempt_test_belongs_to_course
 foreign key(course_id,test_id) references public.course_tests(course_id,id) not valid;
exception when duplicate_object then null; end $$;
do $$ begin
 alter table public.test_attempts add constraint attempt_result_check check(
 score is null or (score between 0 and 100 and (passed is not true or (completed_at is not null and not timed_out and completed_at < expires_at and score >= passing_score_snapshot)))) not valid;
exception when duplicate_object then null; end $$;
create index if not exists enrollments_course_idx on public.enrollments(course_id);
create index if not exists progress_section_idx on public.section_progress(section_id);
create index if not exists blocks_file_path_idx on public.content_blocks(file_path) where file_path is not null;
create index if not exists certificates_course_idx on public.certificates(course_id);
create index if not exists courses_catalog_idx on public.courses(created_at desc,id);
create or replace function public.app_readiness() returns text language sql security definer set search_path='' as $$ select 'aquageo-2'; $$;
revoke all on function public.app_readiness() from public,anon,authenticated;
grant execute on function public.app_readiness() to service_role;
-- Trigger functions are never callable by API roles.
revoke all on function public.protect_certificate_snapshot(),public.audit_entity(),public.snapshot_course_revision() from public,anon,authenticated;

grant select on public.profiles,public.courses to service_role;
-- Auth confirms the new email before updating auth.users.email. Keep the private profile in sync.
create or replace function public.sync_auth_email() returns trigger language plpgsql security definer set search_path='' as $$
begin
 update public.profiles set email=lower(new.email) where id=new.id;
 return new;
end $$;
drop trigger if exists on_auth_email_changed on auth.users;
create trigger on_auth_email_changed after update of email on auth.users for each row when(old.email is distinct from new.email) execute function public.sync_auth_email();
revoke all on function public.sync_auth_email() from public,anon,authenticated;

-- Seminar options and versioned question types. Applied in the same transaction as the core schema.
alter table public.courses add column if not exists academic_hours integer check (academic_hours between 1 and 10000);
alter table public.test_questions add column if not exists question_type text not null default 'single_choice'
  check (question_type in ('single_choice','multiple_choice','true_false','short_answer'));
alter table public.test_question_answers alter column correct_option_id drop not null;
alter table public.test_question_answers add column if not exists correct_option_ids uuid[];
alter table public.test_question_answers add column if not exists accepted_answers text[];
alter table public.certificates add column if not exists academic_hours_snapshot integer;
alter table public.certificates add column if not exists city_snapshot text;
alter table public.certificates add column if not exists template_version integer not null default 2;

-- Never infer hours for existing courses/certificates from free-form duration text.
update public.courses c set certificate = exists(select 1 from public.course_tests t where t.course_id=c.id and t.enabled)
where c.certificate is distinct from exists(select 1 from public.course_tests t where t.course_id=c.id and t.enabled);

create or replace function public.normalize_test_answer(value text) returns text
language sql immutable set search_path='' as $$
  select lower(btrim(regexp_replace(value, '[[:space:]]+', ' ', 'g')));
$$;
revoke all on function public.normalize_test_answer(text) from public,anon,authenticated;

create or replace function public.save_course_test(check_course_id uuid, check_passing_score integer,
  check_time_limit_minutes integer, check_questions jsonb)
returns table(test_id uuid,test_version integer)
language plpgsql security definer set search_path='' as $$
declare
  tid uuid; ver integer; item jsonb; opt jsonb; pos bigint; opos bigint;
  qid uuid; oid uuid; kind text; indices integer[]; correct_ids uuid[];
  accepted text[]; options jsonb; total integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  perform 1 from public.courses where id=check_course_id for update;
  if not public.can_manage_course(check_course_id) then raise exception 'You do not have permission to edit this course test'; end if;
  if check_passing_score is null or check_passing_score not in (60,70,80,90,100) then raise exception 'Invalid passing score'; end if;
  if check_time_limit_minutes is null or check_time_limit_minutes not between 1 and 480 then raise exception 'Invalid time limit'; end if;
  if check_questions is null or jsonb_typeof(check_questions)<>'array' or pg_column_size(check_questions)>1048576 then raise exception 'Invalid questions'; end if;
  total:=jsonb_array_length(check_questions);
  if total not between 1 and 200 then raise exception 'A test must contain 1-200 questions'; end if;
  insert into public.course_tests(course_id,enabled,passing_score,time_limit_minutes,question_count,version)
  values(check_course_id,true,check_passing_score,check_time_limit_minutes,total,1)
  on conflict(course_id) do update set enabled=true,passing_score=excluded.passing_score,
    time_limit_minutes=excluded.time_limit_minutes,question_count=excluded.question_count,version=public.course_tests.version+1
  returning id,version into tid,ver;
  for item,pos in select value,ordinality from jsonb_array_elements(check_questions) with ordinality loop
    kind:=coalesce(item->>'type','single_choice');
    if jsonb_typeof(item)<>'object' or jsonb_typeof(item->'text') is distinct from 'string'
      or char_length(btrim(item->>'text')) not between 1 and 2000
      or kind not in ('single_choice','multiple_choice','true_false','short_answer') then raise exception 'Invalid question'; end if;
    correct_ids:='{}'; accepted:=null;
    insert into public.test_questions(test_id,version,question_text,position,question_type)
    values(tid,ver,btrim(item->>'text'),pos,kind) returning id into qid;
    if kind='short_answer' then
      if jsonb_typeof(item->'acceptedAnswers') is distinct from 'array' then raise exception 'Accepted answers must be an array'; end if;
      if jsonb_array_length(item->'acceptedAnswers') not between 1 and 20 or exists(
        select 1 from jsonb_array_elements(item->'acceptedAnswers') a
        where jsonb_typeof(a)<>'string' or char_length(public.normalize_test_answer(a#>>'{}')) not between 1 and 500
      ) then raise exception 'Invalid accepted answers'; end if;
      select array_agg(distinct public.normalize_test_answer(a)) into accepted from jsonb_array_elements_text(item->'acceptedAnswers') a;
    else
      options:=item->'options';
      if jsonb_typeof(options) is distinct from 'array' then raise exception 'Options must be an array'; end if;
      if jsonb_array_length(options) not between 2 and 6 or (kind='true_false' and jsonb_array_length(options)<>2) then raise exception 'Invalid option count'; end if;
      if kind='multiple_choice' then
        if jsonb_typeof(item->'correctOptionIndices') is distinct from 'array' then raise exception 'Correct indices must be an array'; end if;
        if exists(select 1 from jsonb_array_elements(item->'correctOptionIndices') a where jsonb_typeof(a)<>'number' or (a#>>'{}') !~ '^[0-9]+$') then raise exception 'Invalid correct indices'; end if;
        select array_agg(a::integer) into indices from jsonb_array_elements_text(item->'correctOptionIndices') a;
      else
        if jsonb_typeof(item->'correctOptionIndex') is distinct from 'number' or (item->>'correctOptionIndex') !~ '^[0-9]+$' then raise exception 'Invalid correct index'; end if;
        indices:=array[(item->>'correctOptionIndex')::integer];
      end if;
      if coalesce(cardinality(indices),0)<1 or cardinality(indices)<>(select count(distinct i) from unnest(indices) i)
        or exists(select 1 from unnest(indices) i where i<0 or i>=jsonb_array_length(options)) then raise exception 'Invalid correct indices'; end if;
      for opt,opos in select value,ordinality from jsonb_array_elements(options) with ordinality loop
        if jsonb_typeof(opt)<>'string' or char_length(btrim(opt#>>'{}')) not between 1 and 1000 then raise exception 'Invalid option text'; end if;
        insert into public.test_options(question_id,option_text,position) values(qid,btrim(opt#>>'{}'),opos) returning id into oid;
        if (opos-1)=any(indices) then correct_ids:=array_append(correct_ids,oid); end if;
      end loop;
    end if;
    insert into public.test_question_answers(question_id,correct_option_id,correct_option_ids,accepted_answers)
    values(qid,case when kind in ('single_choice','true_false') then correct_ids[1] else null end,correct_ids,accepted);
  end loop;
  return query select tid,ver;
end;
$$;
-- Only the transactional course editor may call this helper.
revoke all on function public.save_course_test(uuid,integer,integer,jsonb) from public,anon,authenticated;

create or replace function public.submit_course_test(check_attempt_id uuid,check_answers jsonb)
returns table(attempt_id uuid,score integer,correct_answers integer,total_questions integer,passed boolean,
  timed_out boolean,completed_at timestamptz,duration_seconds integer)
language plpgsql security definer set search_path='' as $$
declare
  attempt public.test_attempts%rowtype; question public.test_questions%rowtype; key public.test_question_answers%rowtype;
  payload jsonb:=coalesce(check_answers,'[]'); item jsonb; ids uuid[]; expected uuid[];
  total integer; correct integer:=0; result integer; expired boolean; finished timestamptz; duration integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if jsonb_typeof(payload)<>'array' or pg_column_size(payload)>262144 then raise exception 'Invalid answers'; end if;
  select * into attempt from public.test_attempts a where a.id=check_attempt_id and a.user_id=auth.uid() for update;
  if attempt.id is null then raise exception 'Test attempt not found'; end if;
  if attempt.completed_at is not null then raise exception 'This test attempt has already been submitted'; end if;
  finished:=clock_timestamp();
  select count(*) into total from public.test_questions q where q.test_id=attempt.test_id and q.version=attempt.test_version;
  if jsonb_array_length(payload)>total then raise exception 'Too many answers were submitted'; end if;
  if exists(select 1 from jsonb_array_elements(payload) a group by a->>'question_id' having count(*)>1) then raise exception 'Only one answer per question is allowed'; end if;
  for item in select value from jsonb_array_elements(payload) loop
    if jsonb_typeof(item)<>'object' then raise exception 'Submitted answers contain invalid question or option identifiers'; end if;
    select * into question from public.test_questions q where q.id=(item->>'question_id')::uuid and q.test_id=attempt.test_id and q.version=attempt.test_version;
    if question.id is null then raise exception 'Submitted answers contain invalid question or option identifiers'; end if;
    select * into key from public.test_question_answers a where a.question_id=question.id;
    if question.question_type='short_answer' then
      if jsonb_typeof(item->'text') is distinct from 'string' or char_length(item->>'text')>500 or item ?| array['option_id','option_ids'] then raise exception 'Invalid text answer'; end if;
      if public.normalize_test_answer(item->>'text')=any(key.accepted_answers) then correct:=correct+1; end if;
    else
      if item ? 'text' then raise exception 'Invalid choice answer'; end if;
      if question.question_type='multiple_choice' then
        if jsonb_typeof(item->'option_ids') is distinct from 'array' or item ? 'option_id' then raise exception 'Invalid option set'; end if;
        if jsonb_array_length(item->'option_ids') not between 1 and 6 then raise exception 'Invalid option set'; end if;
        select array_agg(a::uuid) into ids from jsonb_array_elements_text(item->'option_ids') a;
      else
        if jsonb_typeof(item->'option_id') is distinct from 'string' or item ? 'option_ids' then raise exception 'Submitted answers contain invalid question or option identifiers'; end if;
        ids:=array[(item->>'option_id')::uuid];
      end if;
      if cardinality(ids)<>(select count(distinct i) from unnest(ids) i) or exists(
        select 1 from unnest(ids) i where not exists(select 1 from public.test_options o where o.id=i and o.question_id=question.id)
      ) then raise exception 'Submitted answers contain invalid question or option identifiers'; end if;
      expected:=coalesce(nullif(key.correct_option_ids,'{}'::uuid[]),array[key.correct_option_id]);
      if ids @> expected and ids <@ expected then correct:=correct+1; end if;
    end if;
  end loop;
  result:=case when total>0 then round(correct*100.0/total)::integer else 0 end;
  expired:=finished>=attempt.expires_at;
  duration:=greatest(0,round(extract(epoch from(finished-attempt.started_at)))::integer);
  update public.test_attempts set answers=payload,correct_answers=correct,total_questions=total,score=result,
    passed=(not expired and result>=attempt.passing_score_snapshot),timed_out=expired,completed_at=finished,duration_seconds=duration where id=attempt.id;
  return query select attempt.id,result,correct,total,(not expired and result>=attempt.passing_score_snapshot),expired,finished,duration;
end;
$$;
revoke all on function public.submit_course_test(uuid,jsonb) from public,anon;
grant execute on function public.submit_course_test(uuid,jsonb) to authenticated;

create or replace function public.app_readiness() returns text language sql security definer set search_path='' as $$ select 'aquageo-3'; $$;
revoke all on function public.app_readiness() from public,anon,authenticated;
grant execute on function public.app_readiness() to service_role;

NOTIFY pgrst, 'reload schema';
COMMIT;
