-- Generated by npm run sql:build. Supabase SQL Editor: run the WHOLE file.
BEGIN;
SET LOCAL lock_timeout='15s';
SET LOCAL statement_timeout='120s';
-- Apply after the seminars update (aquageo-3).
create or replace function public.save_course_with_content(
  check_course_id uuid,
  check_expected_updated_at timestamptz,
  check_payload jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  course_id_value uuid := check_course_id;
  owner_id_value uuid;
  old_updated_at timestamptz;
  payload_slug text;
  payload_title text;
  section_item jsonb;
  block_item jsonb;
  test_item jsonb;
  section_pos bigint;
  block_pos bigint;
  section_id_value uuid;
  block_id_value uuid;
  section_ids uuid[] := array[]::uuid[];
  block_ids uuid[];
  block_type_value public.content_block_type;
  file_path_value text;
  content_value text;
  has_test boolean;
  hours_value integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if coalesce(public.current_user_role()::text, '') not in ('admin', 'manager') then
    raise exception 'Only admin or manager can edit courses';
  end if;

  if check_payload is null or jsonb_typeof(check_payload) <> 'object' then
    raise exception 'Course payload must be an object';
  end if;
  if pg_column_size(check_payload) > 2097152 then
    raise exception 'Course payload is too large';
  end if;

  payload_title := btrim(coalesce(check_payload->>'title', ''));
  payload_slug := btrim(lower(coalesce(check_payload->>'slug', '')));
  if char_length(payload_title) < 1 or char_length(payload_title) > 300 then
    raise exception 'Course title must contain 1-300 characters';
  end if;
  if char_length(payload_slug) < 1 or char_length(payload_slug) > 160 or payload_slug !~ '^[a-z0-9а-яё-]+$' then
    raise exception 'Course slug is invalid';
  end if;
  if jsonb_typeof(coalesce(check_payload->'sections', '[]'::jsonb)) <> 'array' then
    raise exception 'Course sections must be an array';
  end if;
  if jsonb_array_length(coalesce(check_payload->'sections', '[]'::jsonb)) > 100 then
    raise exception 'A course cannot contain more than 100 sections';
  end if;

  test_item := check_payload->'test';
  if test_item is not null and jsonb_typeof(test_item) not in ('object','null') then raise exception 'Invalid test settings'; end if;
  has_test := coalesce(jsonb_typeof(test_item)='object' and coalesce((test_item->>'enabled')::boolean,true),false);
  hours_value := nullif(check_payload->>'academicHours','')::integer;
  if hours_value is not null and hours_value not between 1 and 10000 then raise exception 'Invalid academic hours'; end if;

  if course_id_value is null then
    insert into public.courses (
      slug, title, category, date_text, duration, format, location,
      image_url, short_description, description, outcomes,
      lecturer_name, lecturer_role, lecturer_bio, lecturer_photo,
      certificate, academic_hours, created_by
    ) values (
      payload_slug,
      payload_title,
      left(btrim(coalesce(check_payload->>'category', '')), 160),
      left(btrim(coalesce(check_payload->>'date', '')), 160),
      left(btrim(coalesce(check_payload->>'duration', '')), 100),
      left(btrim(coalesce(check_payload->>'format', '')), 100),
      left(btrim(coalesce(check_payload->>'location', '')), 240),
      left(btrim(coalesce(check_payload->>'image', '')), 2000),
      left(btrim(coalesce(check_payload->>'shortDescription', '')), 1000),
      left(btrim(coalesce(check_payload->>'description', '')), 20000),
      coalesce(array(select jsonb_array_elements_text(coalesce(check_payload->'outcomes', '[]'::jsonb))), '{}'::text[]),
      left(btrim(coalesce(check_payload#>>'{lecturer,name}', '')), 200),
      left(btrim(coalesce(check_payload#>>'{lecturer,role}', '')), 200),
      left(btrim(coalesce(check_payload#>>'{lecturer,bio}', '')), 5000),
      left(btrim(coalesce(check_payload#>>'{lecturer,photo}', '')), 2000),
      has_test,
      hours_value,
      auth.uid()
    )
    returning id into course_id_value;
  else
    select c.created_by, c.updated_at
      into owner_id_value, old_updated_at
    from public.courses c
    where c.id = course_id_value
    for update;

    if owner_id_value is null then
      raise exception 'Course not found';
    end if;
    if not public.can_manage_course(course_id_value) then
      raise exception 'You do not have permission to edit this course';
    end if;
    if check_expected_updated_at is null or old_updated_at <> check_expected_updated_at then
      raise exception 'COURSE_EDIT_CONFLICT';
    end if;

    update public.courses c set
      slug = payload_slug,
      title = payload_title,
      category = left(btrim(coalesce(check_payload->>'category', '')), 160),
      date_text = left(btrim(coalesce(check_payload->>'date', '')), 160),
      duration = left(btrim(coalesce(check_payload->>'duration', '')), 100),
      format = left(btrim(coalesce(check_payload->>'format', '')), 100),
      location = left(btrim(coalesce(check_payload->>'location', '')), 240),
      image_url = left(btrim(coalesce(check_payload->>'image', '')), 2000),
      short_description = left(btrim(coalesce(check_payload->>'shortDescription', '')), 1000),
      description = left(btrim(coalesce(check_payload->>'description', '')), 20000),
      outcomes = coalesce(array(select jsonb_array_elements_text(coalesce(check_payload->'outcomes', '[]'::jsonb))), '{}'::text[]),
      lecturer_name = left(btrim(coalesce(check_payload#>>'{lecturer,name}', '')), 200),
      lecturer_role = left(btrim(coalesce(check_payload#>>'{lecturer,role}', '')), 200),
      lecturer_bio = left(btrim(coalesce(check_payload#>>'{lecturer,bio}', '')), 5000),
      lecturer_photo = left(btrim(coalesce(check_payload#>>'{lecturer,photo}', '')), 2000),
      certificate = has_test,
      academic_hours = hours_value
    where c.id = course_id_value;
  end if;

  for section_item, section_pos in
    select value, ordinality
    from jsonb_array_elements(coalesce(check_payload->'sections', '[]'::jsonb)) with ordinality
  loop
    if nullif(section_item->>'id', '') is not null then
      section_id_value := (section_item->>'id')::uuid;
      if section_id_value = any(section_ids) then raise exception 'Duplicate section'; end if;
      if not exists (
        select 1 from public.course_sections s
        where s.id = section_id_value and s.course_id = course_id_value
      ) then
        raise exception 'A section does not belong to this course';
      end if;
      update public.course_sections s set
        title = left(btrim(coalesce(section_item->>'title', '')), 300),
        description = left(btrim(coalesce(section_item->>'description', '')), 10000),
        position = section_pos
      where s.id = section_id_value;
    else
      insert into public.course_sections (course_id, title, description, position)
      values (
        course_id_value,
        left(btrim(coalesce(section_item->>'title', '')), 300),
        left(btrim(coalesce(section_item->>'description', '')), 10000),
        section_pos
      ) returning id into section_id_value;
    end if;

    if btrim(coalesce(section_item->>'title', '')) = '' then
      raise exception 'Section title cannot be empty';
    end if;

    section_ids := array_append(section_ids, section_id_value);
    block_ids := array[]::uuid[];

    if jsonb_typeof(coalesce(section_item->'blocks', '[]'::jsonb)) <> 'array' then
      raise exception 'Section blocks must be an array';
    end if;
    if jsonb_array_length(coalesce(section_item->'blocks', '[]'::jsonb)) > 200 then
      raise exception 'A section cannot contain more than 200 blocks';
    end if;

    for block_item, block_pos in
      select value, ordinality
      from jsonb_array_elements(coalesce(section_item->'blocks', '[]'::jsonb)) with ordinality
    loop
      block_type_value := (block_item->>'type')::public.content_block_type;
      file_path_value := nullif(btrim(coalesce(block_item->>'filePath', '')), '');
      content_value := left(coalesce(block_item->>'content', ''), 100000);

      if file_path_value is not null then
        if char_length(file_path_value) > 500 or file_path_value like '%..%' or left(file_path_value, 1) = '/' then
          raise exception 'Invalid course file path';
        end if;
        if not exists (
          select 1
          from storage.objects o
          where o.bucket_id = 'course-files'
            and o.name = file_path_value
            and (
              (o.owner_id = auth.uid()::text or split_part(o.name, '/', 1) = auth.uid()::text)
              or public.current_user_role() = 'admin'
              or exists (
                select 1
                from public.content_blocks old_b
                join public.course_sections old_s on old_s.id = old_b.section_id
                where old_b.file_path = file_path_value
                  and old_s.course_id = course_id_value
              )
            )
        ) then
          raise exception 'Course file is missing or is not owned by this editor';
        end if;
      end if;

      if block_type_value in ('pdf','image','youtube') and file_path_value is null and content_value<>'' and content_value !~ '^https?://' then raise exception 'Material URL must use HTTPS or HTTP'; end if;

      -- Signed/private Storage URLs are bearer credentials. Never persist them in content.
      if file_path_value is not null and block_type_value in ('pdf', 'image') then
        content_value := '';
      end if;

      if nullif(block_item->>'id', '') is not null then
        block_id_value := (block_item->>'id')::uuid;
        if block_id_value = any(block_ids) then raise exception 'Duplicate block'; end if;
        if not exists (
          select 1 from public.content_blocks b
          where b.id = block_id_value and b.section_id = section_id_value
        ) then
          raise exception 'A content block does not belong to this section';
        end if;
        update public.content_blocks b set
          type = block_type_value,
          title = left(btrim(coalesce(block_item->>'title', '')), 500),
          content = content_value,
          file_path = file_path_value,
          position = block_pos
        where b.id = block_id_value;
      else
        insert into public.content_blocks (section_id, type, title, content, file_path, position)
        values (
          section_id_value,
          block_type_value,
          left(btrim(coalesce(block_item->>'title', '')), 500),
          content_value,
          file_path_value,
          block_pos
        ) returning id into block_id_value;
      end if;

      block_ids := array_append(block_ids, block_id_value);
    end loop;

    delete from public.content_blocks b
    where b.section_id = section_id_value
      and not (b.id = any(block_ids));
  end loop;

  if exists (select 1 from public.course_sections s join public.section_progress p on p.section_id=s.id where s.course_id=course_id_value and not (s.id=any(section_ids))) then
    raise exception 'SECTION_HAS_PROGRESS';
  end if;

  delete from public.course_sections s
  where s.course_id = course_id_value
    and not (s.id = any(section_ids));

  test_item := check_payload->'test';
  if has_test then
    perform 1
    from public.save_course_test(
      course_id_value,
      coalesce((test_item->>'passingScore')::integer, 70),
      coalesce((test_item->>'timeLimitMinutes')::integer, 10),
      coalesce(test_item->'questions', '[]'::jsonb)
    );
  else
    update public.course_tests set enabled=false where course_id=course_id_value;
    update public.enrollments e set completed_at=coalesce(e.completed_at,clock_timestamp())
    where e.course_id=course_id_value and public.course_content_completed(course_id_value,e.user_id);
  end if;

  return course_id_value;
end;
$$;

revoke execute on function public.save_course_with_content(uuid, timestamptz, jsonb) from public, anon;
grant execute on function public.save_course_with_content(uuid, timestamptz, jsonb) to authenticated;
-- Participant ratings: identities remain private; only aggregates are public.
create table if not exists public.course_ratings (
  course_id uuid not null references public.courses(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (course_id, user_id)
);
alter table public.course_ratings enable row level security;
revoke all on public.course_ratings from public, anon, authenticated;
grant select on public.course_ratings to authenticated;
drop policy if exists rating_owner_read on public.course_ratings;
create policy rating_owner_read on public.course_ratings for select to authenticated
  using (user_id = auth.uid());

create or replace function public.rate_course(check_course_id uuid, check_rating integer)
returns public.course_ratings
language plpgsql security definer set search_path = '' as $$
declare target public.course_ratings%rowtype;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if check_rating is null or check_rating not between 1 and 5 then
    raise exception 'RATING_INVALID';
  end if;
  -- Share the course-edit lock and derive completion from trusted progress/test data.
  perform 1 from public.courses where id = check_course_id and archived_at is null for share;
  if not found then raise exception 'Course not found'; end if;
  perform public.finalize_course_completion(check_course_id);
  insert into public.course_ratings(course_id, user_id, rating)
    values (check_course_id, auth.uid(), check_rating)
  on conflict (course_id, user_id) do update
    set rating = excluded.rating, updated_at = clock_timestamp()
  returning * into target;
  return target;
end;
$$;
revoke all on function public.rate_course(uuid, integer) from public, anon;
grant execute on function public.rate_course(uuid, integer) to authenticated;

create or replace function public.get_course_rating_summaries(check_course_ids uuid[])
returns table(course_id uuid, rating numeric, rating_count bigint)
language plpgsql stable security definer set search_path = '' as $$
begin
  if coalesce(cardinality(check_course_ids), 0) > 1000 then
    raise exception 'Too many courses';
  end if;
  return query
    select c.id, coalesce(round(avg(r.rating), 1), 5::numeric), count(r.user_id)
    from public.courses c left join public.course_ratings r on r.course_id = c.id
    where c.id = any(check_course_ids)
    group by c.id;
end;
$$;
revoke all on function public.get_course_rating_summaries(uuid[]) from public;
grant execute on function public.get_course_rating_summaries(uuid[]) to anon, authenticated;

NOTIFY pgrst, 'reload schema';
COMMIT;
