import fs from 'node:fs';
const base=fs.readFileSync('supabase/source/base.sql','utf8');
const hardening=fs.readFileSync('supabase/source/hardening.sql','utf8');
const release=fs.readFileSync('supabase/source/release.sql','utf8');
const seminars=fs.readFileSync('supabase/source/seminars.sql','utf8');
const ratings=fs.readFileSync('supabase/source/ratings.sql','utf8');
const preamble=`-- Generated by npm run sql:build. Supabase SQL Editor: run the WHOLE file.\nBEGIN;\nSET LOCAL lock_timeout='15s';\nSET LOCAL statement_timeout='120s';\n`;
// Replay canonical CREATE IF NOT EXISTS definitions for supported historical schemas.
// All grants/policies are replaced within the same transaction, never exposed mid-upgrade.
const suffix="\nNOTIFY pgrst, 'reload schema';\nCOMMIT;\n";
const sql=preamble+base+'\n'+hardening+'\n'+release+'\n'+seminars+'\n'+ratings+suffix;
fs.writeFileSync('supabase/full_schema.sql',sql);
fs.writeFileSync('supabase/migrate_existing_database.sql','-- Existing data retained. Backup first. Conflicts abort the whole transaction.\n'+sql);
const saveStart=hardening.indexOf('create or replace function public.save_course_with_content(');
const saveGrant='grant execute on function public.save_course_with_content(uuid, timestamptz, jsonb) to authenticated;';
const saveEnd=hardening.indexOf(saveGrant,saveStart);
if(saveStart<0||saveEnd<0)throw new Error('Course save function not found');
fs.writeFileSync('supabase/ratings_update.sql',preamble+'-- Apply after the seminars update (aquageo-3).\n'+hardening.slice(saveStart,saveEnd+saveGrant.length)+'\n'+ratings+suffix);
